import {
  Activity,
  AlertTriangle,
  ArrowUpRight,
  Award,
  BadgeCheck,
  BarChart3,
  Bell,
  BookMarked,
  BookOpen,
  Bot,
  Brain,
  Building2,
  Calendar,
  ChartBar,
  ChartColumn,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Circle,
  CircleAlert,
  CircleCheck,
  CircleDollarSign,
  CircleX,
  Clipboard,
  ClipboardCheck,
  ClipboardList,
  Clock,
  Coins,
  Compass,
  Database,
  Dot,
  Download,
  Edit3,
  Eye,
  File,
  FileChartColumn,
  FileQuestion,
  FileStack,
  FileText,
  Filter,
  Flame,
  Gift,
  GraduationCap,
  Handshake,
  Home,
  Hourglass,
  Info,
  Inbox,
  Kanban,
  Landmark,
  Lightbulb,
  ListChecks,
  Mail,
  Map,
  MapPin,
  Medal,
  Megaphone,
  MessageCircle,
  Mic,
  Moon,
  NotebookTabs,
  NotebookText,
  Package,
  PanelTop,
  Percent,
  Phone,
  Pin,
  PlayCircle,
  Plus,
  Presentation,
  Rocket,
  Save,
  Scale,
  School,
  Search,
  Send,
  Shield,
  ShieldCheck,
  Sparkles,
  Sprout,
  SquarePen,
  Star,
  Sun,
  Tag,
  Target,
  TestTube,
  ThumbsDown,
  ThumbsUp,
  Timer,
  Trash2,
  TrendingUp,
  Trophy,
  Upload,
  User,
  UserCheck,
  Users,
  Wrench,
  X,
  Zap,
  type LucideIcon,
} from 'lucide-react';
import type { CSSProperties } from 'react';

const IC: Record<string, LucideIcon> = {
  activity: Activity,
  alert: AlertTriangle,
  'alert-circle': CircleAlert,
  arrowup: ArrowUpRight,
  award: Award,
  badge: BadgeCheck,
  'badge-check': BadgeCheck,
  balance: Scale,
  bell: Bell,
  book: BookOpen,
  'book-marked': BookMarked,
  'book-open': BookOpen,
  bot: Bot,
  brain: Brain,
  building: Building2,
  calendar: Calendar,
  cal: Calendar,
  chart: ChartColumn,
  'chart-bar': ChartBar,
  'chart-line': TrendingUp,
  'chart-no-axis': BarChart3,
  check: Check,
  'chevron-down': ChevronDown,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'chevron-up': ChevronUp,
  circle: Circle,
  'circle-check': CircleCheck,
  'circle-dollar': CircleDollarSign,
  'circle-x': CircleX,
  clipboard: Clipboard,
  'clipboard-check': ClipboardCheck,
  'clipboard-list': ClipboardList,
  clock: Clock,
  coins: Coins,
  compass: Compass,
  database: Database,
  db: Database,
  dot: Dot,
  down: ChevronDown,
  download: Download,
  edit: Edit3,
  'edit-3': Edit3,
  eye: Eye,
  file: FileText,
  'file-chart': FileChartColumn,
  'file-question': FileQuestion,
  'file-stack': FileStack,
  'file-text': FileText,
  filter: Filter,
  flame: Flame,
  gift: Gift,
  graduation: GraduationCap,
  handshake: Handshake,
  home: Home,
  hourglass: Hourglass,
  info: Info,
  inbox: Inbox,
  kanban: Kanban,
  landmark: Landmark,
  lightbulb: Lightbulb,
  list: ListChecks,
  mail: Mail,
  map: Map,
  'map-pin': MapPin,
  medal: Medal,
  megaphone: Megaphone,
  message: MessageCircle,
  mic: Mic,
  moon: Moon,
  notebook: NotebookText,
  'notebook-tabs': NotebookTabs,
  package: Package,
  panel: PanelTop,
  percent: Percent,
  phone: Phone,
  pin: Pin,
  play: PlayCircle,
  plus: Plus,
  presentation: Presentation,
  right: ChevronRight,
  rocket: Rocket,
  save: Save,
  scale: Scale,
  school: School,
  search: Search,
  send: Send,
  shield: Shield,
  'shield-check': ShieldCheck,
  sparkles: Sparkles,
  sprout: Sprout,
  squarepen: SquarePen,
  star: Star,
  sun: Sun,
  tag: Tag,
  target: Target,
  test: TestTube,
  thumbsdown: ThumbsDown,
  thumbsup: ThumbsUp,
  timer: Timer,
  trash: Trash2,
  trend: TrendingUp,
  trophy: Trophy,
  up: ChevronUp,
  upload: Upload,
  user: User,
  'user-check': UserCheck,
  users: Users,
  wrench: Wrench,
  x: X,
  zap: Zap,
};

export function Icon({ name, size = 16, style }: { name: string; size?: number; style?: CSSProperties }) {
  const resolvedName = IC[name] ? name : 'sparkles';
  const IconComponent = IC[resolvedName];

  return (
    <span
      aria-hidden="true"
      data-icon={resolvedName}
      style={{ display: 'inline-flex', flexShrink: 0, width: size, height: size, lineHeight: 0, ...style }}
    >
      <IconComponent size={size} strokeWidth={1.8} />
    </span>
  );
}
